FORMAT: 1A

# NoteTaker
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/api/v1/notes]
### List all Notes [GET]
+ Request (application/json)

    + Header

            X-API-KEY: Your API Key

+ Response 200 (application/json)

        { 
            "notes": [
                {
                    "id": 1, 
                    "title": "Jogging in park",
                    "content": "Before dad flips",
                    "created_at": "2015-01-27T09:20:07.493Z",
                    "updated_at": "2015-01-27T09:20:07.493Z"
                }, {
                    "id": 2, 
                    "title": "Pick-up posters from post-office",
                    "content": "All the cool kids are doing it",
                    "created_at": "2015-01-27T09:20:07.493Z",
                    "updated_at": "2015-01-27T09:20:07.493Z"
                }
            ]
        }

### Create a Note [POST]
+ Request (application/json)

    + Header

            X-API-KEY: Your API Key

    + Body

            {
                "title": "Things to buy for breakfast.",
                "content": "Buy cheese and bread."
            }

+ Response 201 (application/json)

    + Body

            {
                "note": { 
                    "id": 3,
                    "title": "Things to buy for breakfast.",
                    "content": "Buy cheese and bread.",
                    "created_at": "2015-01-27T09:20:07.493Z",
                    "updated_at": "2015-01-27T09:20:07.493Z"
                }
            }

## Note [/api/v1/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `3`) ... Numeric `id` of the Note to perform action with. Has example value.

### Update a Note [PATCH]
+ Request (application/json) 

    + Header

            X-API-KEY: Your API Key
    
    + Body

            {
                "title": "Things to buy for breakfast v2"
            }

+ Response 202 (application/json)

    + Body
    
            { 
                "note": {
                    "id": 3,
                    "title": "Things to buy for breakfast v2",
                    "content": "Buy cheese and bread.",
                    "created_at": "2015-01-27T09:20:07.493Z",
                    "updated_at": "2015-01-27T09:20:07.493Z"
                }
            }

### Retrieve a Note [GET]
+ Request (application/json)

    + Header

            X-API-KEY: Your API Key

+ Response 200 (application/json)

    + Body

            { 
                "note": {
                    "id": 3, 
                    "title": "Things to buy for breakfast v2",
                    "content": "Buy cheese and bread.",
                    "created_at": "2015-01-27T09:20:07.493Z",
                    "updated_at": "2015-01-27T09:20:07.493Z"
                }
            }

### Remove a Note [DELETE]
+ Request (application/json)

    + Header

            X-API-KEY: Your API Key

+ Response 204
